version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/base:stable

jobs:
  # Step 1: Testing
  testing:
    executor: default-executor
    steps:
      - checkout

      # Set up Node.js environment
      - run:
          name: Set up Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run tests
      - run:
          name: Run Tests
          command: npm test

  # Step 2: Build and Push Docker Image
  build-and-push:
    executor: default-executor
    steps:
      - checkout

      # Login to Docker Hub
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

      # Build and tag Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t "$DOCKER_HUB_USERNAME/nestjs-example:latest" .

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker Image
          command: |
            docker push "$DOCKER_HUB_USERNAME/nestjs-example:latest"

      # Update Docker image metadata
      - run:
          name: Update Image Metadata
          command: |
            docker tag "$DOCKER_HUB_USERNAME/nestjs-example:latest" "$DOCKER_HUB_USERNAME/nestjs-example:${CIRCLE_SHA1}"

  # Step 3: Deploy to Render
  deploy:
    executor: default-executor
    steps:
      - run:
          name: Deploy to Render
          command: |
            curl -X POST "$RENDER_DEPLOY_HOOK" \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"image":"$DOCKER_HUB_USERNAME/nestjs-example:latest"}'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - testing
      - build-and-push:
          requires:
            - testing
      - deploy:
          requires:
            - build-and-push
